name: Publish NuGet Package to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
        default: '0.1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' 

    - name: Clean project
      run: dotnet clean ./build/src/PureCloudPlatform.Client.V2/PureCloudPlatform.Client.V2.csproj --configuration Release

    - name: Restoring dependencies
      run: dotnet restore ./build/src/PureCloudPlatform.Client.V2/PureCloudPlatform.Client.V2.csproj

    - name: Building project
      run: dotnet build ./build/src/PureCloudPlatform.Client.V2/PureCloudPlatform.Client.V2.csproj --configuration Release

    - name: Pack NuGet package
      run: dotnet pack ./build/src/PureCloudPlatform.Client.V2/PureCloudPlatform.Client.V2.csproj --configuration Release /p:PackageVersion=${{ github.event.inputs.version }}

    - name: Publish to GitHub Packages
      run: dotnet nuget push './/build/src/PureCloudPlatform.Client.V2/bin/Release/*.nupkg' --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
